[phases.setup]
nixPkgs = ['python311', 'playwright', 'chromium']

[phases.install]
cmds = ['pip install -r requirements.txt', 'playwright install chromium']

[start]
cmd = 'gunicorn run:app --bind 0.0.0.0:$PORT'
